//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Please provide The student name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please provide The student religion")]
        public string Religion { get; set; }
        [EmailAddress(ErrorMessage = "Please provide The student Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please provide The student Address")]
        public string Address { get; set; }
        [Phone(ErrorMessage = "Please provide The student phone")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Please provide The student Institute")]
        public string Institute { get; set; }
    }
}
